{% load_yaml as rawmap %}
FreeBSD:
    package: mysql56
    service: mysql
    config:
        file: /usr/local/etc/my.cnf
        sections:
            mysqld:
                bind-address: 0.0.0.0
                port: 3306
{% endload %}
