{% load_yaml as rawmap %}
FreeBSD:
    server_package: mysql56-server
    client_package: mysql56-client
    pymysql: py27-MySQLdb56
    service: mysql-server
    admin: True
    config:
        file: /usr/local/etc/my.cnf
        sections:
            mysqld:
                bind-address: 0.0.0.0
                port: 3306
    master_user:
        username: root
        password: root
{% endload %}
